receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:

  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name

      - action: insert
        key: environment
        from_attribute: deployment.environment

  batch:

exporters:

  debug:
    verbosity: detailed

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

    default_labels_enabled:
      exporter: false
      job: true

service:
  pipelines:

    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug, loki]