global:
  scrape_interval: 15s   # scrape every 15 seconds
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Dev Auth Server
  - job_name: 'dev-auth-server'
    metrics_path: '/dev-auth-server/actuator/prometheus'
    static_configs:
      - targets: ['dev-auth-server:8000']

#  # Dev Sandbox
#  - job_name: 'dev-sandbox'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8082']
#
#  # Dev Integration
#  - job_name: 'dev-integration'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8083']
